### ISSUE TITLE
Flake checker download not found

### ISSUE THREAD

**Issue by ecarlson94** [DeterminateSystems/flake-checker-action#32]
The nix flake action can't download the checker:

![image](https://github.com/DeterminateSystems/flake-checker-action/assets/6665964/bda34f5a-1ea9-4a50-a8f4-aac3fb0c831f)

https://fiids.install.determinate.systems/flake-checker/stable/X64-Linux (404 Not Found)

```xml
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>v0.1.20/flake-checker-X64-Linux</Key>
    <RequestId>TQCQ7DG397XG760N</RequestId>
    <HostId>
        hCU8qc+oP/H9LPCqugJ9O1HIWO7xyhxG0wDTgjsASe6AbP9m4J0WHkH/AiqJSWdbP0nv64gq5E2RO6ZVvxKgEcT2mc5Q2pmVyDIuTdOgPtw=
    </HostId>
</Error>

**Comment by lucperkins** [comment]
This should be fixed now! Please let us know if not.
