### ISSUE TITLE
Feature idea: check multiple nixpkgs

### ISSUE THREAD

**Issue by dpc** [DeterminateSystems/flake-checker-action#7]
It's quite common for our project to need something from `nixpkgs-unstable`, while we prefer to stick with `nixpkgs/nixos-xx.yy` for everything else.  So [we import nixpkgs twice (actually 3 times, for reasons...) and mix and match](https://github.com/fedimint/fedimint/blob/928cec4993c589d4fa017c99000fbc02149a73b6/flake.nix#L35).

Anyway - would be nice if we could check multiple/other inputs as well.

**Comment by lucperkins** [comment]
@dpc This is actually already possible 😄 You can run this in that repo:

```shell
flake-checker --nixpkgs-keys nixpkgs,nixpkgs-unstable,nixpkgs-kitman
```
